### ISSUE TITLE
ref: add [tool.setuptools] section in pyproject.toml

### ISSUE THREAD

**Issue by ximenesyuri** [f-utils/general#52]
# Description

Now we will add some scripts in a repository `f-{lib}/sh`, we have two root directories, so that one should explicit which will be used  during the build. To do that, add the following section in the `pyproject.toml`:

```toml
[tool.setuptools.packages.find]
where = ["."]
include = ["f_{lib}*"]
```

1. add this in the existing libraries that are missing that section
2. add this in the `f-utils/.template` repository
